Added custom logger
gdscnitp/charges-by-tenant pull request #13
Opened 2021-11-21 13:00 UTC by SihotiyaKartik

2021-11-21 18:11 UTC, rishabhborn2win requested changes
<img width="463" alt="Screenshot 2021-11-21 at 11 39 50 PM" src="https://user-images.githubusercontent.com/55771529/142773867-07ca8a5b-141d-49eb-93f2-b99d9b954264.png">

For all the methods we are getting the same type of color else its working fine.

One more thing to add, is the logs get appended in a single file with the dates and the routes in which the error was.

2021-11-30 04:29 UTC, rishabhborn2win commented
@SihotiyaKartik Update?

2021-11-30 05:20 UTC, rishabhborn2win approved these changes

2021-11-30 06:50 UTC, PalakKumari approved these changes

2021-11-30 06:56 UTC, merged